/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AyarYonetici;
import controller.OyunAyarDialogYonetici;
import controller.OyunYonetici;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.OyunAyar;
import model.Sabitler;

/**
 *
 * @author Mert
 */
public class AnimasyonFrame extends javax.swing.JFrame {

    private boolean basladiMi = false;
    private final AyarYonetici ja = new AyarYonetici(Sabitler.AYAR_DOSYASI);
    private final OyunYonetici oyunYonetici;
    private final OyunAyar ayar;
    private final OyunAyarDialogYonetici oady;

    /**
     * Creates new form AnimasyonFrame
     */
    public AnimasyonFrame() {
        initComponents();
        ayar = ja.jsonOku();
        topButton.setLocation(ayar.getTopXKonumu(), ayar.getTopYKonumu());
        oyunYonetici = new OyunYonetici(topButton);
        oyunYonetici.oyunHiziniAyarla(ayar.getOyunHizi());
        oyunYonetici.topHiziAyarla(ayar.getTopXHizi(), ayar.getTopYHizi());
        oady = new OyunAyarDialogYonetici(oyunYonetici, ayarDialog);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ayarDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        oyunHizTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        topXHizTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        topYHizTextField = new javax.swing.JTextField();
        ayarKaydetButton = new javax.swing.JButton();
        animasyonPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        animasyonButton = new javax.swing.JButton();
        ayarButton = new javax.swing.JButton();
        kaydetButton = new javax.swing.JButton();

        ayarDialog.setTitle("Ayarlar");
        ayarDialog.setAlwaysOnTop(true);
        ayarDialog.setMinimumSize(new java.awt.Dimension(350, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(null, null), null, null, null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Oyun Hızı : ");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 25));

        oyunHizTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oyunHizTextField.setText("10");
        oyunHizTextField.setPreferredSize(new java.awt.Dimension(110, 25));
        oyunHizTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyunHizTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Top X Hızı : ");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 25));

        topXHizTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topXHizTextField.setText("2");
        topXHizTextField.setPreferredSize(new java.awt.Dimension(110, 25));
        topXHizTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topXHizTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Top Y Hızı : ");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 25));

        topYHizTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topYHizTextField.setText("2");
        topYHizTextField.setPreferredSize(new java.awt.Dimension(110, 25));

        ayarKaydetButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ayarKaydetButton.setText("Kaydet");
        ayarKaydetButton.setPreferredSize(new java.awt.Dimension(100, 30));
        ayarKaydetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayarKaydetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(topYHizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(topXHizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(oyunHizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(ayarKaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oyunHizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topXHizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topYHizTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(ayarKaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ayarDialogLayout = new javax.swing.GroupLayout(ayarDialog.getContentPane());
        ayarDialog.getContentPane().setLayout(ayarDialogLayout);
        ayarDialogLayout.setHorizontalGroup(
            ayarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ayarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ayarDialogLayout.setVerticalGroup(
            ayarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ayarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Top Oyunu");

        animasyonPanel.setBackground(new java.awt.Color(204, 204, 204));
        animasyonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(null, null));
        animasyonPanel.setPreferredSize(new java.awt.Dimension(680, 414));
        animasyonPanel.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(null));

        animasyonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animasyonButtonActionPerformed(evt);
            }
        });

        ayarButton.setText("Ayarlar");
        ayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayarButtonActionPerformed(evt);
            }
        });

        kaydetButton.setText("Kaydet");
        kaydetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(animasyonButton)
                .addGap(99, 99, 99)
                .addComponent(ayarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(animasyonButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(ayarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kaydetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(animasyonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(animasyonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oyunHizTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyunHizTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oyunHizTextFieldActionPerformed

    private void topXHizTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topXHizTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topXHizTextFieldActionPerformed

    private void ayarKaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayarKaydetButtonActionPerformed
        oady.oyunBilgileriniAyarla(Integer.parseInt(oyunHizTextField.getText()), Double.parseDouble(topXHizTextField.getText()), Double.parseDouble(topYHizTextField.getText()));
        oady.dialogKapat();
        animasyonButton.setEnabled(true);
    }//GEN-LAST:event_ayarKaydetButtonActionPerformed

    private void animasyonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animasyonButtonActionPerformed
        if (basladiMi) {
            oyunYonetici.oyunuDurdur();
            basladiMi = false;
            ayarButton.setEnabled(true);
            animasyonButton.setIcon(new ImageIcon(Sabitler.DURDUR_RESIM));
        } else {
            oyunYonetici.oyunuBaslat();
            animasyonButton.setIcon(new ImageIcon(Sabitler.BASLAT_RESIM));
            ayarButton.setEnabled(false);
            basladiMi = true;
        }
    }//GEN-LAST:event_animasyonButtonActionPerformed

    private void ayarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayarButtonActionPerformed
        oady.dialogGoster();
    }//GEN-LAST:event_ayarButtonActionPerformed

    private void kaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButtonActionPerformed
        ayar.setTopXKonumu(topButton.getLocation().x);
        ayar.setTopYKonumu(topButton.getLocation().y);
        ayar.setTopXHizi(topButton.getxHizi());
        ayar.setTopYHizi(topButton.getyHizi());
        ayar.setOyunHizi(oyunYonetici.getOyunHizi());
        boolean yazildiMi = ja.jsonOlustur(ayar);
        if (yazildiMi) {
            JOptionPane.showMessageDialog(rootPane, "Ayarlar kaydedildi", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_kaydetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimasyonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimasyonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimasyonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimasyonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimasyonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton animasyonButton;
    private javax.swing.JPanel animasyonPanel;
    private javax.swing.JButton ayarButton;
    private javax.swing.JDialog ayarDialog;
    private javax.swing.JButton ayarKaydetButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JTextField oyunHizTextField;
    private javax.swing.JTextField topXHizTextField;
    private javax.swing.JTextField topYHizTextField;
    // End of variables declaration//GEN-END:variables
}
